// LOGIN TO THE APP
###
POST http://localhost:3006/auth/login 
content-type: application/json

{
    "email": "admin@demo.com",
    "password": "demo"
}

// GET USER INFORMATIONS
###
GET http://localhost:3006/auth/profile 
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhOTc3MTI2NS1iMGYxLTQyOWMtODZlOS00NWU3OTdiZGVlMjQiLCJpYXQiOjE2NDk3MzQ0Mjk1MDAsImV4cCI6MTY0OTczNDQyOTUwMH0.WgJ8QeQCgBu-zSAQ2tqMOZmt-m17KqrteoqG28LoVC8mKww2PJ4Ilx1wN39EIvjs3WEqP2_3OMOZlknzr61kFdIzWO_1SAvK4QJ7WQIaSQZNc5eYUEfVnDFAra-T6if9zNQjXAXEm1HC6swlwGKZesQZ3QD6yrv-SvT0TBcipJ0iiCKzWhQhVke8trHzUPqX92EzwzgJUjgJFbpQ5KqNBXQUCvwpAtdLGmfe3V8hOw29GLTpK-nw-onAVHJ3DGHzR2V7sm8ZInASrouGlWo62bd1G0stHsJCe6aDWuc_RywBQ0eCxzBfo8cvYbTELKplsCfnYmUttBaICUhxXh79vYjuxGgRM22aIUngLAXQYAdbpn1qs3GUGYWOwJmZOpXp3YapdDs9FHZOAIpaOQS2731fdD3nqqnYVsPgiV3TKeXPd-lGm7Sbj91zXh0pthdm6mpBQuGeQdpvzd-nh9MigGs7NkdvphT8g68jZ0G9MobBNb3T7HaT-wLZTAwMYbzGejSbcs2ALljYB9ASaDHKbU_I9YX3E97x-KDYJ0QzrK52GAqRotSHjofh5ueCPSgEZrIlaeTpu2z63kq_4YjPlpiUK9mnP5hh_b5K37FVbUPcM543Gc7JafrfWSKDKKn-lVcjY8S0Okw_kjUWynklRcdwzVoXv3vaT1dhO7gpjN0
