//
//------------- GET ALL USERS ----------------
//
###
GET http://localhost:3006/users 
content-type: application/json


//
//------------- GET ONE USER ----------------
//
###
GET http://localhost:3006/users/a9771265-b0f1-429c-86e9-45e797bdee24
content-type: application/json


//
//------------- UPDATE ONE USER ----------------
//
###
PUT http://localhost:3006/users/a9771265-b0f1-429c-86e9-45e797bdee24
content-type: application/json

{
    "username": "admin",
    "email": "admin@demo.com",
    "firstname": "Desire",
    "lastname": "ARRA",
    "fullname": "Desire ARRA",
    "roles": "ROLE_USER",
    "pic": "/media/users/300_21.jpg",
    "language": "fr",
    "timeZone": "International Date Line West",
    "isEnabled": true
}

//
//------------- CHANGE USER PASSWORD ----------------
//
###
PATCH http://localhost:3006/users/change-password
content-type: application/json

{
    "_id": "61faa328c770a4106ace2541",
    "password": "demo2",
    "newPassword": "demo"
}

//
//------------- USER REGISTRATION ----------------
//
###
POST http://localhost:3006/users/registration
Content-Type: application/json

{
    "email": "admin@demo.com",
    "password": "demo",
    "firstName": "Desire",
    "lastName": "ARRA",
    "role": "ROLE_ADMIN"
}